version: '3.8'


services:

  stats-server:
    build: stats/stats-server
    image: stats-server
    container_name: stats-server
    ports:
      - "9090:9090"

    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/explore_with_me
      - POSTGRES_DB=explore_with_me
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=iamroot

  stats-db:
      image: postgres:14.6-alpine
      container_name: stats-db
      ports:
        - "6541:5432"
      environment:
        - POSTGRES_DB=explore_with_me
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=iamroot


