
CREATE TABLE IF NOT EXISTS comments
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    text          VARCHAR(20000)                          NOT NULL,
    user_id       BIGINT                                  NOT NULL,
    event_id      BIGINT                                  NOT NULL,
    created       TIMESTAMP WITHOUT TIME ZONE,
    state_comment VARCHAR(10)                             NOT NULL,
    update    BOOLEAN,
    views         BIGINT,
    CONSTRAINT pk_comment PRIMARY KEY (id),
    CONSTRAINT uc_comment_text UNIQUE (text),
    CONSTRAINT FK_COMMENT_ON_EVENT FOREIGN KEY (event_id) REFERENCES events (event_id),
    CONSTRAINT FK_COMMENT_ON_USER FOREIGN KEY (user_id) REFERENCES users (id)
);
